name: Feature PR to Development

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request to Development
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: PR automático da feature para development'
          title: 'Feature para Development: ${{ github.ref_name }}'
          body: 'PR automático criado a partir da branch ${{ github.ref_name }}'
          base: development
          branch: ${{ github.ref_name }}
          delete-branch: false
